### ISSUE TITLE
host switched to default value

### ISSUE THREAD

**Issue by krzysieki** [jsoverson/rcl#6]
Hi

If we specify custom host with:
rcl.connect('1.2.3.4','8888');

and socket.io script is downloaded with function:
includeSocketIo

then host is switched back to "127.0.0.1" because of:
onLoadIo

onLoadIo calls connect without parameters

BTW
thanks for this great tool!

**Comment by jimmed** [comment]
The following pull request should fix this issue: https://github.com/jsoverson/rcl/pull/7
